### ISSUE TITLE
Используйте early exit вместо вложенных условий

### ISSUE THREAD

**Issue by coursar** [rustamSurmashev/znakZodiac#2]
https://github.com/rustamSurmashev/znakZodiac/blob/0e9ac11cbef6ba66083651a52cd609ff6a045d23/src/js/zodiac.js#L4-L17

**Comment by rustamSurmashev** [comment]
@coursar, применен ранний выход.
Выполнено в addd02a31df1a4ed625936ec42a3dde97a1b4996
